# Sample workflow for building and deploying a Jekyll site to GitHub Pages
name: Deploy Jekyll with GitHub Pages dependencies preinstalled

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Build job
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Build with Jekyll
        uses: actions/jekyll-build-pages@v1
        with:
          source: ./
          destination: ./_site
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
      # Add the following steps to install Node.js with NVM, install Yarn, and start your project
      - name: Install Git
        run: |
          sudo apt-get update
          sudo apt-get install git -y
      - name: Clone Repository
        run: git clone https://github.com/j13Lucas/j13Lucas.github.io.git
      - name: Change to Repository Directory
        run: cd j13Lucas.github.io  # Replace with your actual repository folder
      - name: List Files
        run: ls
      - name: Install Node.js with NVM
        run: |
          curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.39.1/install.sh | bash
          export NVM_DIR="$HOME/.nvm"
          [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
          [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
          nvm install 14  # Install the desired Node.js version
          nvm use 14      # Use the installed Node.js version
          
      - name: Install Yarn
        run: |
          npm install -g yarn
          
      - name: List Files
        run: ls
        
      - name: Start Your Project with Yarn
        run: |
          yarn install
          yarn start
 
      - name: Build with Yarn
        run: |
          yarn build
      - name: Deploy with Yarn
        run: |
          yarn deploy
